name: Build unstable image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build-unstable:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit
